services:
  # WSTREAM API
  wstream-api:
    build:
      context: .
      dockerfile: src/UzTube.API/Dockerfile
    image: wstream-api:dev
    container_name: wstream-api
    environment:
    # ASPNETCORE 
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_ENVIRONMENT=${ASPNET_ENVIRONMENT}
      # DATABASE
      - ConnectionStrings__DefaultConnection=Server=${DB_SERVER};Port=${DB_PORT};Database=${DB};User Id=${DB_USER};Password=${DB_PASSWORD};
      # JWT 
      - JwtSettings__SecretKey=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      # SMTP 
      - SmtpSettings__Username=${EMAIL_USERNAME}
      - SmtpSettings__Password=${EMAIL_PASSWORD}
      # SERILOG
      - Serilog__WriteTo__1__Name=${LOG_WRITE_TO}
      - Serilog__WriteTo__1__Args__serverUrl=${SEQ_URL}:${SEQ_PORT}
      # MEDIAMTX
      - StreamSettings__RtmpServer=${MEDIAMTX_RTMP_SERVER}
      - StreamSettings__RtmpPort=${MEDIAMTX_RTMP_PORT}
      - StreamSettings__HlsServer=${MEDIAMTX_HLS_URL}
      - StreamSettings__HlsPort=${MEDIAMTX_HLS_PORT}
      # MINIO
      - MinioSettings__Url=${MINIO_URL}
      - MinioSettings__Server=${MINIO_SERVER}
      - MinioSettings__Port=${MINIO_PORT}
      - MinioSettings__AccessKey=${MINIO_ACCESS_KEY}
      - MinioSettings__SecretKey=${MINIO_SECRET_KEY}
      - MinioSettings__UseSSL=false
    ports:
      - "${API_CONTAINER_PORT}:${API_CONTAINER_PORT}"
    depends_on:
      - wstream-database
      - wstream-logs
      - wstream-filemanager
    networks:
      - wstream-network
    restart: unless-stopped
  
  # PostgreSQL
  wstream-database:
    image: postgres:latest
    container_name: wstream-database
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # - /home/wwlinux/projects/wstream/development/wstream-database:/var/lib/postgresql
      - wstream-database:/var/lib/postgresql
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - wstream-network
    restart: unless-stopped
    
  # SEQ
  wstream-logs:
    image: datalust/seq:latest
    container_name: wstream-logs
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINUSERNAME: ${SEQ_FIRSTRUN_ADMINUSERNAME}
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_FIRSTRUN_ADMINPASSWORD}
    ports:
      - "${SEQ_PORT}:5341"
      - "${SEQ_URL_PORT}:80"
    volumes:
      - wstream-logs:/data
    networks:
      - wstream-network
    restart: unless-stopped
    
  # MediaMTX
  wstream-streammanager:
    build:
      context: ./mediamtx
      dockerfile: Dockerfile
    image: wstream-streammanager:custom
    container_name: wstream-streammanager
    ports:
      - "${MEDIAMTX_RTMP_PORT}:1935"       # RTMP
      - "${MEDIAMTX_HLS_PORT}:8888"        # HLS
     #  - "8554:8554"                      # RTSP
     #  - "8889:8889"                      # WebRTC HTTP
     #  - "8189:8189/udp"                  # WebRTC UDP
     #  - "8189:8189/tcp"                  # WebRTC TCP fallback
     #  - "8890:8890/udp"                  # SRT
     #  - "9997:9997"                      # API
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
    networks:
      - wstream-network

  # MinIO
  wstream-filemanager:
     image: minio/minio:latest
     container_name: wstream-filemanager
     command: server --console-address ":9001" /data/
     environment:
       MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
       MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
     ports:
       - "${MINIO_URL_PORT}:9001"
       - "${MINIO_PORT}:9000"
     volumes:
       - wstream-filemanager:/data
     networks:
       - wstream-network
     restart: unless-stopped

  wstream-filemanager-init:
    image: minio/mc:latest
    depends_on:
      - wstream-filemanager
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set wstream http://wstream-filemanager:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      mc mb --ignore-existing wstream/avatars;
      mc mb --ignore-existing wstream/videos;
      mc mb --ignore-existing wstream/previews;
      mc anonymous set download wstream/avatars;
      mc anonymous set download wstream/videos;
      mc anonymous set download wstream/previews;
      exit 0;"
    networks:
      - wstream-network
      
  # Nginx
  wstream-nginx:
    image: nginx:latest
    container_name: wstream-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # CONF
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled/wstream.uz:/etc/nginx/sites-enabled/wstream.uz:ro
      - ./nginx/sites-enabled/api.wstream.uz:/etc/nginx/sites-enabled/api.wstream.uz:ro
      - ./nginx/sites-enabled/files.wstream.uz:/etc/nginx/sites-enabled/files.wstream.uz:ro
      - ./nginx/sites-enabled/stream.wstream.uz:/etc/nginx/sites-enabled/stream.wstream.uz:ro
      - ./nginx/sites-enabled/logs.wstream.uz:/etc/nginx/sites-enabled/logs.wstream.uz:ro
      - ./nginx/sites-enabled/wwlinux.uz:/etc/nginx/sites-enabled/wwlinux.uz:ro
      # SSL
      - ./nginx/ssl/letsencrypt/wstream.uz:/etc/letsencrypt/live/wstream.uz:ro
      - ./nginx/ssl/letsencrypt/api.wstream.uz:/etc/letsencrypt/live/api.wstream.uz:ro
      - ./nginx/ssl/letsencrypt/files.wstream.uz:/etc/letsencrypt/live/files.wstream.uz:ro
      - ./nginx/ssl/letsencrypt/stream.wstream.uz:/etc/letsencrypt/live/stream.wstream.uz:ro
      - ./nginx/ssl/letsencrypt/logs.wstream.uz:/etc/letsencrypt/live/logs.wstream.uz:ro
      - ./nginx/ssl/letsencrypt/wwlinux.uz:/etc/letsencrypt/live/wwlinux.uz:ro
      # SSL OPTIONS
      - ./nginx/ssl/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - ./nginx/ssl/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
      # LOG
      # - /home/wwlinux/projects/wstream/development/wstream-nginx-logs:/var/log/nginx
      - wstream-nginx-logs:/var/log/nginx
      # PROJECT
      - /home/wwlinux/projects:/home/wwlinux/projects:ro
    depends_on:
      - wstream-api
    networks:
      - wstream-network
    restart: unless-stopped

volumes:
  wstream-database:
    name: wstream-database
  wstream-logs:
    name: wstream-logs
  wstream-filemanager:
    name: wstream-filemanager
  wstream-nginx-logs:
    name: wstream-nginx-logs
    
networks:
  wstream-network:
    driver: bridge