services:
  # UzTube API Application
  uztube_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: uztube:dev
    container_name: uztube_api
    environment:
      # ASPNETCORE 
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_ENVIRONMENT=${ASPNET_ENVIRONMENT}
      # DATABASE
      - ConnectionStrings__DefaultConnection=Server=uztube_database;Database=${DB};User Id=${DB_USER};Password=${DB_PASSWORD};
      # JWT 
      - JwtSettings__SecretKey=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      # SMTP 
      - SmtpSettings__Username=${EMAIL_USERNAME}
      - SmtpSettings__Password=${EMAIL_PASSWORD}
      # SERILOG
      - Serilog__WriteTo__1__Name=${LOG_WRITE_TO}
      - Serilog__WriteTo__1__Args__serverUrl=${SEQ_URL}
    expose:
      - "4444"
    depends_on:
      - uztube_database
      - uztube_logs
    networks:
      - uztube_network
    restart: unless-stopped
    
  # Serilog (Seq)
  uztube_logs:
    image: datalust/seq:latest
    container_name: uztube_logs
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINUSERNAME: ${SEQ_FIRSTRUN_ADMINUSERNAME}
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_FIRSTRUN_ADMINPASSWORD}
    ports:
      - "5341:5341" # Seq ingestion port
      - "8080:80"   # Seq UI port (optional, adjust if needed)
    volumes:
      - uztube_logs:/data # Persistent storage for Seq data
    networks:
      - uztube_network
    restart: unless-stopped
  
  # PostgreSQL Database
  uztube_database:
    image: postgres:latest
    container_name: uztube_database
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - uztube_database:/var/lib/postgresql
    networks:
      - uztube_network
    restart: unless-stopped

  # Nginx reverse proxy
  uztube_nginx:
    image: nginx:latest
    container_name: uztube_nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - uztube_api
    networks:
      - uztube_network
    restart: unless-stopped

volumes:
  uztube_database:
    name: uztube_database
  uztube_logs:
    name: uztube_logs
    
networks:
  uztube_network:
    driver: bridge